### PR TITLE
Fixed docker-compose configuration

### PR DESCRIPTION
**Pull request by ultranoobian**
Fixes database busy or unavailable error when using 'docker-compose up'

### CODE REVIEW

**Comment by Eeems** [comment]
From what I'm seeing in https://docs.docker.com/compose/compose-file/#build I'm confused as to why this would change anything.

EDIT: Actually, this would completely break the build. The docker compose file is meant to build the docker image from the local docker file. If you want to use the published image, you should be using your own docker-compose.

**Comment by Eeems** [comment]
Since this breaks the intended use of the docker-compose configuration I'm closing this file. Feel free to open a new pull request adding a new sample docker-compose configuration that people can use, or adding it to the readme.

**Comment by ultranoobian** [comment]
Part of the reason why I made this pull request was so that the docker compose configuration reflected the docker run command.

But the issue seems to be that when you build your local docker image from this repositorys docker file, the database settings are not being set properly.

I've asked on the Reddit docker community, for[ reasons why this occurs](http://reddit.com/r/docker/comments/ctbptz/having_problems_translating_docker_run_command_to/exk3ljv) and this user pointed out that it may not be set correct.

I'm not trying to argue how to use the docker compose configuration, just trying to provide a working base without resorting to having the user edit their configuration before running.

I also failed to mention that #1 doesn't occur when I use the proposed docker-compose configuration vs. docker run command in the Read Me

**Comment by Eeems** [comment]
So what you are really looking for is a sample docker-compose configuration to be added to the readme. The docker-compose included in the repository is meant for use with the dockerfile.

**Comment by ultranoobian** [comment]
As far I've tested, the current Dockerfile and/or Docker-compose configuration do not work at the moment, But I think I should open an issue rather than discuss that here. If it works for everyone else, then this PR should really just exist as a sample in the README instead.

Edit: I don't mean to say that it doesn't work at all, just that some configuration is not bring applied when the image is being built.

**Pull request closed without merging**
